interface GenerationResult {
  projectName: string;
  stack: string[];
  scripts: string[];
  envVars: string[];
  deployment: string[];
  dependenciesCount: number;
  fileCount: number;
  modelLabel?: string;
}

function Badge({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-block border border-border px-2 py-0.5 text-xs font-mono bg-card text-foreground">
      {children}
    </span>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="border-b border-border/40 py-2 last:border-b-0">
      <div className="text-[10px] font-bold tracking-[0.2em] uppercase text-muted-foreground mb-1.5">{label}</div>
      <div className="flex flex-wrap gap-1.5">{children}</div>
    </div>
  );
}

export function AnalysisSummary({ data }: { data: GenerationResult }) {
  return (
    <div className="border border-border bg-card p-4">
      <div className="text-xs font-bold tracking-[0.15em] uppercase mb-3 flex items-center justify-between">
        <span>Detected Metadata</span>
        <span className="text-primary">{data.fileCount} files</span>
      </div>
      {data.modelLabel && (
        <div className="mb-3 flex items-center gap-1.5 text-[11px] font-mono text-muted-foreground">
          <span className="inline-block w-1.5 h-1.5 bg-primary shrink-0" />
          generated by {data.modelLabel}
        </div>
      )}
      <Row label="Stack">
        {data.stack.length ? (
          data.stack.map((s) => <Badge key={s}>{s}</Badge>)
        ) : (
          <span className="text-xs text-muted-foreground">unknown</span>
        )}
      </Row>
      <Row label={`Scripts (${data.scripts.length})`}>
        {data.scripts.length ? (
          data.scripts.slice(0, 10).map((s) => <Badge key={s}>{s}</Badge>)
        ) : (
          <span className="text-xs text-muted-foreground">none</span>
        )}
      </Row>
      <Row label={`Env Vars (${data.envVars.length})`}>
        {data.envVars.length ? (
          data.envVars.slice(0, 12).map((s) => <Badge key={s}>{s}</Badge>)
        ) : (
          <span className="text-xs text-muted-foreground">none detected</span>
        )}
      </Row>
      <Row label="Deployment">
        {data.deployment.length ? (
          data.deployment.map((s) => <Badge key={s}>{s}</Badge>)
        ) : (
          <span className="text-xs text-muted-foreground">none detected</span>
        )}
      </Row>
      <Row label="Dependencies">
        <Badge>{data.dependenciesCount} packages</Badge>
      </Row>
    </div>
  );
}
